### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by connecteev** [xinnks/xns-audio-player#1]
The UI looks great but I can't get it to work.
Not sure what's wrong here. Steps I followed:

1. git clone https://github.com/xinnks/xns-audio-player.git
2. cd xns-audio-player/
3. npm install
4. npm run dev

Error:
```
$ npm run dev

> xns-audio-player@1.0.0 dev /Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xns-audio-player@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xns-audio-player@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kunalpunjabi/.npm/_logs/2019-06-27T20_13_24_927Z-debug.log
```

**Comment by xinnks** [comment]
Fixed it by scaffolding the whole code with vue-cli 3, it's an old repo that I never worked on for some time really. Feel free to work with it.

**Comment by connecteev** [comment]
@xinnks thanks for the quick turn! I'm going to try it out, will let you know if I encounter any issues.

**Comment by connecteev** [comment]
@xinnks I'm still seeing an error with a fresh build on my Mac. Let me know if I missed anything here.

$ npm run serve

```
$ npm run serve

> xns-audio-player@0.1.0 serve /Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin                                                    

 ERROR  Failed to compile with 1 errors                                                                                                                                                          10:59:39 AM

 error  in ./src/assets/style.scss

Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~bulma/bulma.sass';
^
      File to import not found or unreadable: ~bulma/bulma.sass.
      in /Users/kunalpunjabi/Code/vuejs_examples/xns-audio-player/src/assets/style.scss (line 2, column 1)

 @ ./src/assets/style.scss 4:14-224 14:3-18:5 15:22-232
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.12:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 


```
